# lightning.pytorch==2.1.2
seed_everything: 13

trainer:
  accelerator: gpu
  devices: 1
  precision: 32-true
  max_epochs: 4
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./logs
      name: m1-local
  callbacks:
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: plane_val_loss_epoch
      patience: 10
      mode: min
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: ./models
      filename: best-{epoch:03d}-{plane_val_loss_epoch:.5f}
      monitor: plane_val_loss_epoch
      mode: min
      save_top_k: 1
      save_last: true

model:
  amount_of_plane_normals_predicted: 32
  amount_of_axis_discrete_normals_predicted: 0
  amount_of_axis_continue_normals_predicted: 0
  w1: 1.0
  w2: 0.0
  w3: 0.0
  eps: 0.01
  theta: 0.00015230484
  confidence_threshold: 0.01
  rot_angle_threshold: 0.0174533
  cost_matrix_method: src.model.matchers.cost_matrix_methods.calculate_cost_matrix_normals
  print_losses: false
  use_bn: false
  normalize_normals: true
  encoder: pointnet
  n_points: 8192

data:
  dataset_path: "C:/datasets/symmetria/Symmetria-Easy-10k/sym-10k-xz-v1.0-repack-rotprob0.5-onlyrotx"
  batch_size: 1
  n_workers: 2
  transform:
    class_path: src.dataset.transforms.ComposeTransform.ComposeTransform
    init_args:
      transforms:
      - class_path: src.dataset.transforms.FarthestPointSampling.FarthestPointSampling
        init_args:
          n_points: 8192
          start: centroid
          keep_cache: false
      - class_path: src.dataset.transforms.UnitSphereNormalization.UnitSphereNormalization
        init_args:
          eps: 1.0e-9
          keep_cache: false
  collate_function: src.dataset.SymDataModule.custom_collate_fn
  shuffle: true

ckpt_path: null
