# lightning.pytorch==2.1.2
seed_everything: 13

trainer:
  accelerator: gpu
  devices: 1
  precision: 32-true
  max_epochs: 2

  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./logs
      name: m1-sanity-check
  
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: train_loss 
        patience: 10
        mode: min
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./models
        filename: best-{epoch:03d}-{train_loss:.5f}
        monitor: train_loss
        mode: min
        save_top_k: 1
        save_last: true

model:
  learning_rate: 0.0001
  amount_of_plane_normals_predicted: 8
  w_conf: 1.0
  w_vec: 1.0
  w_cent: 1.0
  input_channels: 3
  n_points: 1024

data:
  dataset_path: "C:/datasets/symmetria-fps-1024/Symmetria-Easy-10k/sym-10k-xz-v1.0-repack-rotprob0.5-onlyrotx"
  batch_size: 8
  n_workers: 2
  shuffle: true
  
  transform:
    class_path: src.dataset.transforms.ComposeTransform.ComposeTransform
    init_args:
      transforms:
      # - class_path: src.dataset.transforms.FarthestPointSampling.FarthestPointSampling # o RandomSubSample.RandomSubSample si lo tienes así
      #   init_args:
      #     num_points: 1024
      - class_path: src.dataset.transforms.UnitSphereNormalization.UnitSphereNormalization
        init_args:
          eps: 1.0e-9
          keep_cache: false