seed_everything: 13

trainer:
  accelerator: gpu
  devices: [1]           # ¡CLAVE! Esto te ancla a la GPU 1, dejando a ncaytuir en la 0.
  precision: 32-true
  max_epochs: 150        # Límite alto; el EarlyStopping lo detendrá si deja de aprender.

  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./logs
      name: m1-easy-10k-full
  
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss # OJO: Cambiamos a val_loss para evitar sobreajuste (overfitting).
        patience: 15      # Espera 15 épocas sin mejora antes de abortar.
        mode: min
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./models
        filename: best-{epoch:03d}-{val_loss:.5f}
        monitor: val_loss
        mode: min
        save_top_k: 3     # Guarda los 3 mejores modelos históricos.
        save_last: true

model:
  learning_rate: 0.0001
  amount_of_plane_normals_predicted: 8
  w_conf: 1.0
  w_vec: 1.0
  w_cent: 1.0
  input_channels: 3
  n_points: 1024

data:
  # Ajusta esta ruta a tu carpeta principal o directamente a la carpeta "train"
  dataset_path: "/home/vimunoz/proyectos/symmetria-fps-1024/Symmetria-Easy-10k"
  batch_size: 64         # Aprovechamos la VRAM gigante de la A6000.
  n_workers: 4           # Mantenemos 0 para asegurar que no ocurra el EOFError de Linux.
  persistent_workers: true
  shuffle: true
  
  transform:
    class_path: src.dataset.transforms.ComposeTransform.ComposeTransform
    init_args:
      transforms:
      - class_path: src.dataset.transforms.UnitSphereNormalization.UnitSphereNormalization
        init_args:
          eps: 1.0e-9
          keep_cache: false