seed_everything: 13

trainer:
  accelerator: gpu
  devices: [0]
  precision: 32-true
  max_epochs: 200

  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./logs
      name: intermediate-2-10k-32
  
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss # OJO: Cambiamos a val_loss para evitar sobreajuste (overfitting).
        patience: 50      # Espera 50 épocas sin mejora antes de abortar.
        mode: min
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: best-{epoch:03d}-{val_loss:.5f}
        monitor: val_loss
        mode: min
        save_top_k: 3     # Guarda los 3 mejores modelos históricos.
        save_last: true

model:
  learning_rate: 0.001
  amount_of_plane_normals_predicted: 32
  w_conf: 1.0
  w_vec: 1.0
  w_cent: 1.0
  w_rsd: 0.1
  input_channels: 3
  n_points: 1024
  hidden_dim: 128    # <-- ¡El doble de "ancho"! (Por defecto era 128)
  num_oa_layers: 4    # <-- ¡Dos capas más "profundo"! (Por defecto era 4)

data:
  dataset_path: "/data/vimunoz/Symmetria-Intermediate-2-10k-preproc"
  batch_size: 32
  n_workers: 0
  persistent_workers: false
  shuffle: true
  transform:
    class_path: src.dataset.transforms.IdentityTransform.IdentityTransform